apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wordpress
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Hosting Wordpress Deployments

  sourceRepos:
  - 'https://github.com/Ineb01/*'

  destinations:
  - namespace: wordpress
    server: https://kubernetes.default.svc
    name: in-cluster

